[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython>=0.28.5",
    "numpy==1.11.3; python_version<='3.6'",
    "numpy==1.14.5; python_version=='3.7'",
    "numpy==1.17.3; python_version=='3.8'",
    "numpy==1.19.4; python_version>='3.9'",
    "scipy>=0.19.1"
]